# Generated by Django 4.2 on 2023-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_monthly_plan_yearly_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelled_plan',
            name='yr_mon',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='purchased_plan',
            name='yr_mon',
            field=models.CharField(default='mon', max_length=200),
        ),
    ]
